version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Installing Maven"
      - apt-get install -y maven
  pre_build:
    commands:
      - echo "Cleaning old build artifacts"
      - mvn clean
  build:
    commands:
      - echo "Building the project"
      - mvn package -B -DskipTests
  post_build:
    commands:
      - echo "Build completed. Preparing artifact for Elastic Beanstalk"
      # Rename the WAR file to ROOT.war for Elastic Beanstalk Tomcat deployments
      - mkdir -p target/deploy
      - cp target/*.war ROOT.war

artifacts:
  files:
    - ROOT.war
